---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: discord
  namespace: flux-system
spec:
  channel: notifs
  secretRef:
    name: discord-url
  type: discord
  username: FluxCDBot