---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: bookinfo
  namespace: flux-system
spec:
  dependsOn:
  - name: istio-system
  interval: 24h0m0s
  path: ./samples/bookinfo/platform/kube/bookinfo.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: istio
  targetNamespace: default

