---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  dependsOn:
  - name: sops-secrets
  interval: 24h0m0s
  path: ./infra/external-dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

