---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: notes-frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: notes-frontend
  policy:
    semver:
      range: '>1.0.0-develop < 2.0.0-develop'

