---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 24h0m0s
  path: ./kube-prometheus-stack
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system