---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pod-monitors
  namespace: flux-system
spec:
  dependsOn:
  - name: infra
  interval: 1m0s
  path: ./infra/pod-monitors
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

