---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: newrelic
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nri-bundle
      sourceRef:
        kind: HelmRepository
        name: newrelic
  install:
    createNamespace: true
  interval: 24h0m0s
  targetNamespace: newrelic
  values:
    global:
      cluster: civo-flux
      customSecretName: newrelic-license
      customSecretLicenseKey: licenseKey
      lowDataMode: true
    newrelic-infrastructure:
      privileged: true
      integrations_config:
        - name: nri-nginx
          data:
            discovery:
              command:
                # Use the following optional arguments:
                # --namespaces: Comma separated list of namespaces to discover pods on
                # --tls: Use secure (TLS) connection
                # --port: Port used to connect to the kubelet. Default is 10255
                exec: /var/db/newrelic-infra/nri-discovery-kubernetes
                match:
                  label.app: nginx
            integrations:
              - name: nri-nginx
                env:
                  # If you're using ngx_http_api_module be certain to use the full path up to and including the version number
                  # Use the discovered IP as the host address
                  STATUS_URL: http://${discovery.ip}/status
                  # Name of Nginx status module OHI is to query against. discover | ngx_http_stub_status_module | ngx_http_status_module | ngx_http_api_module
                  STATUS_MODULE: discover
                  METRICS: 1
                  REMOTE_MONITORING: 1
    ksm:
      enabled: true
    prometheus:
      enabled: true
    kubeEvents:
      enabled: true
    logging:
      enabled: true
    newrelic-pixie:
      enabled: true
      customSecretApiKeyName: newrelic-license
      customSecretApiKeyKey: pixieApiKey
    pixie-chart:
      enabled: true
      clusterName: civo-flux
      deployKey: px-dep-3432f300-2ee2-46d8-8298-ddb0d2221b1d
      pemMemoryLimit: "1Gi"
      pod:
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "1Gi"