---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: newrelic
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nri-bundle
      sourceRef:
        kind: HelmRepository
        name: newrelic
  install:
    createNamespace: true
  interval: 24h0m0s
  targetNamespace: newrelic
  values:
    global:
      cluster: civo-flux
      customSecretName: newrelic-license
      customSecretLicenseKey: licenseKey
      lowDataMode: true
    newrelic-infrastructure:
      privileged: true
    ksm:
      enabled: true
    prometheus:
      enabled: true
    kubeEvents:
      enabled: true
    logging:
      enabled: true
    newrelic-pixie:
      enabled: true
      customSecretApiKeyName: newrelic-license
      customSecretApiKeyKey: pixieApiKey
    pixie-chart:
      enabled: true
      clusterName: civo-flux
      deployKey: px-dep-3432f300-2ee2-46d8-8298-ddb0d2221b1d
      pemMemoryLimit: "1Gi"
      pod:
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "1Gi"