apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: notes-frontend
  namespace: flux-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://harbor.k8s.stiforr.tech/chartrepo/stiforr
      chart: notes-frontend
      version: 0.2.0
      sourceRef:
        kind: HelmRepository
        name: stiforr
        namespace: flux-system
  interval: 10m0s
  targetNamespace: default
  values:
    fullnameOverride: "notes-frontend"
    image:
      repository: harbor.k8s.stiforr.tech/stiforr/notes-frontend # {"$imagepolicy": "flux-system:notes-frontend:name"}
      tag: "1.3.0-develop.22" # {"$imagepolicy": "flux-system:notes-frontend:tag"}
    api:
      url: http://strapi-backend.k8s.local:8080
    ingress:
      enabled: false
      annotations:
        kubernetes.io/ingress.class: istio
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: notes.test.stiforr.tech
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: notes-frontend-tls
          hosts:
            - notes.test.stiforr.tech
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
