---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 24h0m0s
  targetNamespace: kube-system
  values:
    sources:
      - ingress
    provider: cloudflare
    cloudflare:
      secretName: "cloudflare-secret"
    domainFilters:
      - stiforr.tech
    dryRun: false