---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: strapi-backend
  namespace: flux-system
spec:
  chart:
    spec:
      chart: strapi-backend
      sourceRef:
        kind: HelmRepository
        name: stiforr
  interval: 1m0s
  targetNamespace: default
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: istio
      hosts:
        - host: strapi-backend.k8s.local
          paths:
            - path: /
              pathType: Prefix
    resources:
      #      limits:
      #        cpu: 100m
      #        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    autoscaling:
      minReplicas: 1
      maxReplicas: 5
      targetCPUUtilizationPercentage: 75