---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: notes-frontend
  namespace: flux-system
spec:
  chart:
    spec:
      chart: notes-frontend
      sourceRef:
        kind: HelmRepository
        name: stiforr
  interval: 10m0s
  targetNamespace: default
  values:
    repository: https://harbor.k8s.stiforr.tech/stiforr/notes-frontend
    api:
      url: http://notes-backend:8080
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: istio
      hosts:
        - host: notes.k8s.local
          paths:
            - path: /
              pathType: Prefix