apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: notes-frontend
  namespace: flux-system
spec:
  chart:
    spec:
      chart: notes-frontend
      version: 0.1.16
      sourceRef:
        kind: HelmRepository
        name: stiforr
  interval: 10m0s
  targetNamespace: default
  values:
    fullnameOverride: "notes-frontend"
    image:
      repository: harbor.k8s.stiforr.tech/stiforr/notes-frontend # {"$imagepolicy": "flux-system:notes-frontend:name"}
      tag: "1.3.0-develop.22" # {"$imagepolicy": "flux-system:notes-frontend:tag"}
    api:
      url: http://strapi-backend.k8s.local:8080
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: istio
      hosts:
        - host: notes.test.stiforr.tech
          paths:
            - path: /
              pathType: Prefix
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
