---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
  interval: 24h0m0s
  targetNamespace: cert-manager
  install:
    createNamespace: true
  values:
    installCRDs: true
    clusterResourceNamespace: "kube-system"
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true