kind: Namespace
apiVersion: v1
metadata:
  name: monitoring
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus
      interval: 1m
  install:
    createNamespace: true
  targetNamespace: monitoring
  values:
    alertmanager:
      enabled: false
    grafana:
      enabled: true
      plugins: [ ]
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: istio
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - grafana.test.stiforr.tech
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.test.stiforr.tech
      sidecar:
        dashboards:
          searchNamespace: ALL
    prometheus:
      prometheusSpec:
        podMonitorSelectorNilUsesHelmValues: false
        podMonitorSelector: { }
#          matchLabels:
#            app.kubernetes.io/part-of: flux