kind: Namespace
apiVersion: v1
metadata:
  name: monitoring
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus
      interval: 1m
  install:
    crds: Create
    createNamespace: true
  upgrade:
    crds: CreateReplace
  targetNamespace: monitoring
  values:
    alertmanager:
      enabled: false
    grafana:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: istio
        hosts:
          - grafana.k8s.local
      sidecar:
        dashboards:
          searchNamespace: ALL
    prometheus:
      prometheusSpec:
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/part-of: flux