kind: Namespace
apiVersion: v1
metadata:
  name: monitoring
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
      interval: 1m
  targetNamespace: monitoring
  values:
    fullnameOverride: "kube-prometheus-stack"
    alertmanager:
      enabled: false
    grafana:
      enabled: true
      plugins: [ ]
      persistence:
        type: pvc
        enabled: true
        # storageClassName: default
        accessModes:
          - ReadWriteOnce
        size: 10Gi
        # annotations: {}
        finalizers:
          - kubernetes.io/pvc-protection
        inMemory:
          enabled: false
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: istio
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - grafana.test.stiforr.tech
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.test.stiforr.tech
      sidecar:
        dashboards:
          enabled: true
          searchNamespace: ALL
    prometheus:
      prometheusSpec:
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/part-of: flux