---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: remix-jokes
  namespace: flux-system
spec:
  chart:
    spec:
      chart: remix-jokes
      sourceRef:
        kind: HelmRepository
        name: stiforr
  interval: 24h0m0s
  releaseName: remix-jokes
  targetNamespace: default
  values:
    image:
      repository: stiforr/remix-jokes
      pullPolicy: IfNotPresent
      tag: "latest"
    ingress:
      enabled: true
      #      className: "istio"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: istio
      hosts:
        - host: remix-jokes.k8s.stiforr.tech
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: remix-jokes-tls
          hosts:
            - remix-jokes.k8s.stiforr.tech