---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: remix-jokes
  namespace: flux-system
spec:
  chart:
    spec:
      chart: remix-jokes
      version: 0.2.3
      sourceRef:
        kind: HelmRepository
        name: stiforr
  interval: 24h0m0s
  releaseName: remix-jokes
  targetNamespace: default
  values:
    image:
      repository: stiforr/remix-jokes
      pullPolicy: IfNotPresent
      tag: "latest"
    ingress:
      enabled: false