---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kiali-operator
      sourceRef:
        kind: HelmRepository
        name: kiali
  interval: 24h0m0s
  targetNamespace: istio-system
  values:
    cr:
      create: true
      namespace: istio-system