apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - source-bitnami.yaml
  - source-istio.yaml
  - source-jetstack.yaml
  - source-kiali.yaml
  - source-monitoring.yaml
  - source-newrelic.yaml
  - source-prometheus.yaml
  - source-stiforr.yaml