---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgres
  namespace: flux-system
spec:
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 24h0m0s
  targetNamespace: default
  values:
    persistence:
      enabled: true
      size: 5Gi
    metrics:
      enabled: true
    global:
      postgresql:
        postgresqlDatabase: "test"
        existingSecret: "postgres-secret"