---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kiali-operator
      sourceRef:
        kind: HelmRepository
        name: kiali
  interval: 24h0m0s
  targetNamespace: istio-system
  values:
    cr:
      create: true
      namespace: istio-system
      spec:
        deployment:
          accessible_namespaces:
            - '**'
          pod_labels:
            sidecar.istio.io/inject: "true"
        external_services:
          grafana:
            enabled: true
            in_cluster_url: 'http://monitoring-kube-prometheus-stack-grafana.monitoring'
            url: 'http://grafana.test.stiforr.tech'
            auth:
              type: bearer
              token: "secret:kiali-token:token"
          discovery_enabled: true