apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: treats-portfolio
  namespace: flux-system
spec:
  chart:
    spec:
      # renovate: registryUrl=https://harbor.k8s.stiforr.tech/chartrepo/stiforr
      chart: treats-portfolio
      version: 0.22.1
      sourceRef:
        kind: HelmRepository
        name: stiforr
        namespace: flux-system
  interval: 1m
  targetNamespace: default
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    image:
      repository: stiforr/treats-portfolio # {"$imagepolicy": "flux-system:treats-portfolio:name"}
      tag: "8.6.0-develop.22" # {"$imagepolicy": "flux-system:treats-portfolio:tag"}
