apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: treats-portfolio
  namespace: flux-system
spec:
  chart:
    spec:
      chart: treats-portfolio
      version: 0.21.14
      sourceRef:
        kind: HelmRepository
        name: stiforr
        namespace: flux-system
  interval: 1m
  targetNamespace: default
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    image:
      repository: stiforr/treats-portfolio # {"$imagepolicy": "flux-system:treats-portfolio:name"}
      tag: "8.6.0-develop.15" # {"$imagepolicy": "flux-system:treats-portfolio:tag"}
    #    podAnnotations:
    #      prometheus.io/scrape: "true"
    istio:
      enabled: false
      hosts:
        - treats.test.stiforr.tech
    flagger:
      enabled: true
      analysis:
        interval: 1m
        threshold: 5
        stepWeight: 10
        maxWeight: 100
        metrics:
          - name: request-success-rate
            thresholdRange:
              min: 99
            interval: 1m
          - name: request-duration
            thresholdRange:
              max: 500
            interval: 1m
    ingress:
      enabled: false
      #      className: "istio"
      annotations:
        #        nginx.ingress.kubernetes.io/service-upstream: "true"
        kubernetes.io/ingress.class: istio
      hosts:
        - host: treats.test.stiforr.tech
          paths:
            - path: /
              pathType: ImplementationSpecific
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "250m"
        memory: "256Mi"