---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: istio-operator
      sourceRef:
        kind: HelmRepository
        name: stiforr
  interval: 24h0m0s

