---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 24h0m0s
  ref:
    branch: master
  url: https://github.com/istio/istio

