apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: treats-portfolio
  namespace: flux-system
spec:
  chart:
    spec:
      chart: treats-portfolio
      version: 0.21.13
      sourceRef:
        kind: HelmRepository
        name: stiforr
  interval: 1m
  targetNamespace: default
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    image:
      repository: stiforr/treats-portfolio # {"$imagepolicy": "flux-system:treats-portfolio:name"}
      tag: "8.6.0-develop.15" # {"$imagepolicy": "flux-system:treats-portfolio:tag"}
    istio:
      enabled: true
      hosts:
        - "treats.k8s.local"
    flagger:
      enabled: true
    ingress:
      enabled: false
      #      className: "istio"
      annotations:
        #        nginx.ingress.kubernetes.io/service-upstream: "true"
        kubernetes.io/ingress.class: istio
      hosts:
        - host: treats.k8s.local
          paths:
            - path: /
              pathType: ImplementationSpecific
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
