---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: treats-portfolio
  namespace: flux-system
spec:
  chart:
    spec:
      chart: treats-portfolio
      sourceRef:
        kind: HelmRepository
        name: stiforr
  interval: 1m
  targetNamespace: default
  install:
    remediation:
      retries: 10
  upgrade:
    remediation:
      retries: 10
  values:
    image:
      repository: stiforr/treats-portfolio # {"$imagepolicy": "flux-system:treats-portfolio:name"}
      tag: "8.6.0-develop.2" # {"$imagepolicy": "flux-system:treats-portfolio:tag"}
    flagger:
      enabled: true
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/service-upstream: "true"
      hosts:
        - host: treats.k8s.local
          paths:
            - path: /
              pathType: ImplementationSpecific