kind: Gateway
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: ingress-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
    - port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        mode: SIMPLE
        credentialName: istio-ingress-cert
      hosts:
        - "*"