kind: Service
apiVersion: serving.knative.dev/v1
metadata:
  name: serverless-function
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: ubuntu:20.04
          command:
            - sh -c echo "Hello World"