#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
#kind: Kustomization
#metadata:
#  name: infra-post
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: cert-manager
#    - name: kube-prometheus-stack
#    - name: external-dns
#  interval: 24h0m0s
#  path: ./cluster/infra/infra-post
#  prune: false
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#    namespace: flux-system
#
