---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-base
  namespace: flux-system
spec:
  interval: 24h0m0s
  path: ./cluster/infra/istio/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-operator
  namespace: flux-system
spec:
  interval: 24h0m0s
  dependsOn:
    - name: istio-base
  path: ./cluster/infra/istio/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-system
  namespace: flux-system
spec:
  interval: 24h0m0s
  dependsOn:
    - name: istio-operator
  path: ./cluster/infra/istio/system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system