#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
#kind: Kustomization
#metadata:
#  name: kiali
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: istio-operator
#  interval: 24h0m0s
#  path: ./cluster/infra/kiali
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#    namespace: flux-system