---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: pod-monitors
  namespace: flux-system
spec:
  dependsOn:
    - name: kube-prometheus-stack
  interval: 10m0s
  path: ./cluster/infra/pod-monitors
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system