apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secret
    namespace: kube-system
type: Generic
data:
    cloudflare_api_token: ENC[AES256_GCM,data:FXQO5XYmAQcVqjS4aZsleg1r8JQCQFOwQf6lH7HGPFAwXTjzgsm65A==,iv:TYnrHYWlGwUvNCbqsjYhy6EGnZvkltWrhfksQs8ettA=,tag:zfmrwIw2UflSgyePX+8EHg==,type:str]
    cloudflare-email: ENC[AES256_GCM,data:qdMhu2RPIEzx2DTRFrDBu+0oJKmf3g==,iv:sKofMqnlFKiBbFvdGE27UyxKO/UII03VlxIb9ZxFADg=,tag:o7ofEKvjhFfnAMOLnN3qcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-09T00:21:13Z"
    mac: ENC[AES256_GCM,data:ByZcW1lhuQPRuLo4+pXj7taDIVuQFzZ6DK7VxSWeARHcsEKwnvmoDBMwDsmUXSHNwRaCUn3ai3nBtAh4doY4Ena3+etocVL9l3T+Nmh1yzj6hXAvE21zUgnoSVbMNJ5QyJ75u/iBrDbUtvjjYHVR3Yd596GYT9ix56FcYVDt0dQ=,iv:WR73kv+uP4YOLhtPF69fDdWasKQlpTbV4p9O2hHOZoo=,tag:1AzzGsIYzW1tMmxc4o7b9Q==,type:str]
    pgp:
        - created_at: "2021-11-09T00:21:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwbJWFCdJZWwAQ/9G/J2LpiDGnffBzjS3JwfOPpzVpnqdV6PksPMdYzp0wZB
            YjkrYZ96VKV7CGkn55b+sSpGtxdanaXnOdBgu3koLxBSndrYvK0k9o9PK0NbLcm3
            PGbZfFib/Xq/918zJz41e9MChSjg4MlFSZ3xeaOLx4t9FhaYemiKTLyD6UTfSajA
            I+eT9dPDK4WaAdS+86qgPdTgrX0tZM+rbHWqkoqevX0Ch7S4nriz8tIAfKWHpTiJ
            9BSiG0qknq0kcTkLfoCkyi2pxlQoJXYDnT1g0K4Txn1kOlOZOWoHOzLHj0WqdsMU
            sF/qemjGpewlZnCrTC453WaZA5kVV4kRtSJq9Qg0p/CEEHYTmGndiPng7ygzbUvb
            yYw6b0rVjNhjJ9dBCiLeDpyHjplpgjCZXtflRFtNcTNPWPF/uiSqlsB/caKNLieN
            xzP5YHwjq3121BlJta6nohV4s9d1KGb0csGgiwQjAwqLzFajZMSFS3b2siWDzn3x
            ntVmahNtugUz8bQnnGWopdh1CUAdLEsF72ipDSrhjdV+hCdNn3DkKd8ou2H25zQl
            PlVoI2otbMYGxbuIPgI80abuVsokUbR33qS4EBVF26MH3Mw7l/80VupAru8NJRFI
            OjGBYrQMttRxpvlLc4UCsvzBMWz/ZIDYgtcKuFZR59FhGbeS9ir5fH5SJPKLJYvS
            XgHUAjx+P9Lv+n75ZaeEPFV6ua9zm1lI94ScQl9wuJ3MldPdog8Qb1CFBf74c1Jw
            JySFggSp5hhHemTVmwt20vlBxUFcE4L6MkojTLDFMRlP6ZnEXs521hV7tgKun5g=
            =fYPH
            -----END PGP MESSAGE-----
          fp: 1CD99ADC695765876E9B11658C3AE730765E27E7
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
