apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: postgres-secret
    namespace: default
    labels:
        kustomize.toolkit.fluxcd.io/name: sops-secrets
        kustomize.toolkit.fluxcd.io/namespace: flux-system
data:
    jwt-key: ENC[AES256_GCM,data:n897qptwq851OI9MbVpMouHrwAgJJYt9eVvaqQiKnQYM48TW3NVu+Fc2Wa4=,iv:13qMFilx4Phfl77ko3unGa7UpkembtGef9nnM4i047U=,tag:NnjYfx9ovtwmGDrR5cIBnA==,type:str]
    password: ENC[AES256_GCM,data:Xq208iHviR5iq4jgnO9OMw==,iv:zSRnvG59L/tMYqKEnZCMC/mhQB2Q9KsQj1g224/frVU=,tag:MsmcJQh30Kq4GUD2hYY/NA==,type:str]
    username: ENC[AES256_GCM,data:71DH2lDCj3RgbSSR,iv:q4ApF8PJOJAQbf6vNIkPJaynqw8RFl6a5C5JsY7cONs=,tag:7PGHN3Qmejk0eMw49mLV8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-05T15:50:30Z"
    mac: ENC[AES256_GCM,data:tqTwqMkznePPNBUO4aUPwBOe7mhPo4QBQNw94uy8GXe+sJMMOCvcFcyBt/9kfJAdIXhWKWU0EByc7naChrsUQF3IHNz5Hh3CXbkPBfPliLu+1wZ9P8PeOvpd0Po3t/uUZp260sEQtE/14HAUx2yAeej89K5WlCAJ4i5Of3PBRhk=,iv:2B3AxF2yyRi9FESQ22z/H/pF7dFjboZDK+axwIBc4ws=,tag:xcAoUaDIW8ZOoMldlmZ3+w==,type:str]
    pgp:
        - created_at: "2021-11-05T15:50:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwbJWFCdJZWwARAAiNk4avLL8okUjQnUDMsUHhR7bs0EMcDgyZUWc1fx/Eun
            y8yA7DVxdbXd9LvGfpoDA1bv8SsL/rMU1jJCC+CRBGRmXTVUxXguL1xVkSzIPi9o
            uvyxxWYYtXKA++8F5igs3Z2SWw6Qp6PJyuD9aent3AvFVMzavS9ht8JztjRS7G8j
            GzVqjyd0136IWiV1YWMvgYKZps8lRKR97T5wLr/BdD9Nw8HnplD00WQA2g6Rr+Tb
            giSZ/BBcHTswijqjOXgIsks4UjmEfMY7HWne4aS9hcXyeRUg7prBGorET8RAa9XV
            I8vlPliodyLryFZv8uUMaxwPoMrxmfS9oSU6zKWX0SJ92ynyumRpMQidDoCHjDFK
            ZyDMiYXNP3ANvNIvMgha/ys1cAG7KVZ+htqtXdBc32wub3m9jLzWKx7OSPoAu6GN
            ytBoIqlHaAIi+snmx/05ebRGu3862fdLYmZghtWnSDIJAIs2E6JGnhs2Tai7P1na
            j6gfKgHEx4ijCKF+5ymOVAyjQGuUx/p5+hYONQmj6ofwRTtU09h2GRuIdXE8b44N
            zXrzwskfGwTIl37IZKa8kyVcRiRuHkYp6YvOkGQ3SSolw6IlgqzWJvcK1c6BDC3V
            4zjHai0ZtS0l2ewbZPNmFPR08k2j1PVQ5EkZxgjLQPB3FCCLhw8Nj3q+KwlSRxXS
            XAEOPVxTHM3f9XrIyikq1W/k7FdYtb4NxeTLlzxegkBZW4YS6/P48MSb1gLMuuHj
            Cf+OOihtBexBTWXDljZ7dya57ZW3AtfXPU8QRTn0OihTz+6rfRi96bcQYrJ1
            =u0Jr
            -----END PGP MESSAGE-----
          fp: 1CD99ADC695765876E9B11658C3AE730765E27E7
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
